name: Lockfile Update (one-off)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install (generate lockfile)
        run: npm install

      - name: Commit lockfile
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update package-lock.json for react-helmet-async"
          file_pattern: "package-lock.json"
